[package]
name = "pusz"
version = "0.1.0"
authors = ["fulara"]
edition = "2018"

[dependencies]
inputbot = "0.4.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

glib = "0.8"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_24"]

[dependencies.gio]
version = ""
features = ["v2_44"]

